#!/usr/bin/env bash
# One-shot installer for InfluxDB v2 OSS + Grafana on the Pi.
# Idempotent: re-running is safe.
#
# Usage (on the Pi):
#   bash deploy/install-services.sh
#
# After it finishes, the script writes /home/scott/solarcontrol/.env with the
# InfluxDB connection details (URL, org, bucket, token). The solarcontrol
# systemd unit reads that file via EnvironmentFile=.

set -euo pipefail

INFLUX_ORG="solarcontrol"
INFLUX_BUCKET="solarcontrol"
INFLUX_USER="${SUDO_USER:-${USER}}"   # the human-facing admin user
INFLUX_RETENTION="0"                  # 0 = infinite

ENV_FILE="${HOME}/solarcontrol/.env"

log() { printf '\033[1;34m[svc]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[svc]\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1) InfluxDB v2 OSS via the official InfluxData apt repo
# ---------------------------------------------------------------------------
if ! command -v influx >/dev/null 2>&1 || ! systemctl list-unit-files | grep -q '^influxdb.service'; then
    log "Adding InfluxData apt repo"
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://repos.influxdata.com/influxdata-archive.key \
        | sudo gpg --dearmor -o /etc/apt/keyrings/influxdata-archive.gpg
    DISTRO_CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
    echo "deb [signed-by=/etc/apt/keyrings/influxdata-archive.gpg] https://repos.influxdata.com/debian ${DISTRO_CODENAME} stable" \
        | sudo tee /etc/apt/sources.list.d/influxdata.list >/dev/null
    sudo apt-get update -y
    sudo apt-get install -y influxdb2 influxdb2-cli
fi

log "Enabling and starting influxdb"
sudo systemctl enable --now influxdb

# Wait for it to come up
for i in {1..30}; do
    if curl -fsS http://127.0.0.1:8086/health >/dev/null 2>&1; then break; fi
    sleep 1
done

# ---------------------------------------------------------------------------
# 2) Initial setup (creates org, bucket, admin user, admin token).
#    `influx setup` is a no-op once setup has happened, so guard it.
# ---------------------------------------------------------------------------
SETUP_DONE="$(curl -fsS http://127.0.0.1:8086/api/v2/setup | python3 -c 'import sys,json; print(json.load(sys.stdin)["allowed"])')"
if [[ "${SETUP_DONE}" == "True" ]]; then
    log "Running first-time influx setup"
    # Generate a strong random admin password; user can rotate via the UI later.
    ADMIN_PW="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | cut -c1-24)"
    influx setup --force \
        --username "${INFLUX_USER}" \
        --password "${ADMIN_PW}" \
        --org "${INFLUX_ORG}" \
        --bucket "${INFLUX_BUCKET}" \
        --retention "${INFLUX_RETENTION}" \
        --name default >/dev/null
    log "InfluxDB admin user: ${INFLUX_USER}"
    log "InfluxDB admin password (save this): ${ADMIN_PW}"
else
    log "InfluxDB already initialized; skipping setup"
fi

# ---------------------------------------------------------------------------
# 3) Create (or fetch) a write-only token for the solarcontrol app.
# ---------------------------------------------------------------------------
APP_TOKEN_DESC="solarcontrol-app"

# Look for an existing token by description.
APP_TOKEN_JSON="$(influx auth list --user "${INFLUX_USER}" --json 2>/dev/null \
    | python3 -c "
import sys, json
for a in json.load(sys.stdin):
    if a.get('description') == '${APP_TOKEN_DESC}':
        print(json.dumps(a)); break
" )"

if [[ -z "${APP_TOKEN_JSON}" ]]; then
    log "Creating ${APP_TOKEN_DESC} token (read+write on bucket ${INFLUX_BUCKET})"
    BUCKET_ID="$(influx bucket list --org "${INFLUX_ORG}" --name "${INFLUX_BUCKET}" --json \
        | python3 -c 'import sys,json;print(json.load(sys.stdin)[0]["id"])')"
    APP_TOKEN="$(influx auth create \
        --org "${INFLUX_ORG}" \
        --description "${APP_TOKEN_DESC}" \
        --read-bucket "${BUCKET_ID}" \
        --write-bucket "${BUCKET_ID}" \
        --json \
        | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])')"
else
    APP_TOKEN="$(echo "${APP_TOKEN_JSON}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])')"
    log "${APP_TOKEN_DESC} token already exists; reusing"
fi

# ---------------------------------------------------------------------------
# 4) Write/update the .env file the systemd unit consumes.
# ---------------------------------------------------------------------------
log "Writing ${ENV_FILE}"
mkdir -p "$(dirname "${ENV_FILE}")"
umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by deploy/install-services.sh — safe to edit, but INFLUX_TOKEN
# must match an Influx token that can write to the ${INFLUX_BUCKET} bucket.
INFLUX_URL=http://127.0.0.1:8086
INFLUX_ORG=${INFLUX_ORG}
INFLUX_BUCKET=${INFLUX_BUCKET}
INFLUX_TOKEN=${APP_TOKEN}
EOF
chmod 600 "${ENV_FILE}"

# ---------------------------------------------------------------------------
# 5) Grafana via the official Grafana apt repo
# ---------------------------------------------------------------------------
if ! command -v grafana-server >/dev/null 2>&1; then
    log "Adding Grafana apt repo"
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://apt.grafana.com/gpg.key \
        | sudo gpg --dearmor -o /etc/apt/keyrings/grafana.gpg
    echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" \
        | sudo tee /etc/apt/sources.list.d/grafana.list >/dev/null
    sudo apt-get update -y
    sudo apt-get install -y grafana
fi

log "Enabling and starting grafana-server"
sudo systemctl enable --now grafana-server

log "Done."
log ""
log "Reach Grafana at:        http://${HOSTNAME}:3000   (default admin / admin)"
log "Reach InfluxDB UI at:    http://${HOSTNAME}:8086"
log ""
log "Wrote ${ENV_FILE} (mode 600). Restart solarcontrol to pick it up:"
log "    sudo systemctl restart solarcontrol"
